language: python

python:
  - "3.8"

services:
  - postgresql

addons:
  postgresql: "12"

install:
  # python deps
  - python -m pip install --upgrade pip
  - pip install -r requirements/local.txt
  # yarn deps

before_script:
  - psql -c "CREATE DATABASE obsidian;" -U postgres

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py runserver